### ISSUE TITLE
sym: Outdated documentation & spurious undefined value

### ISSUE THREAD

**Issue by qian-feng** [paradise-fi/divine#1]
Hi, I am Qian, and trying to use divine for the symbolic verification. By following the tutorial(https://divine.fi.muni.cz/manual.html#symbolic-verification), I added  _SYM into my demo c code, as well as "domains/domains.h", but it seems that it always failed at compilation time. Did i miss any libraries when to support symbolic verification? Thanks a lot.

Best,
Qian

**Comment by vlstill** [comment]
Hi, we will need more information to help you with your problem. Can you share the code, the way you are running it in DIVINE and the error messages?

**Comment by qian-feng** [comment]
Hi, I downloaded divine-4.1.5, and tried to use it to conduct the symbolic verification on my test code. The sample code is as following:

#include <stdio.h>
#include <assert.h>
#include "domains/domains.h"
void init( int *array, int len )
{

    if(len<4) return;
    for ( int i = 0; i <= len; ++i )
    {
        printf( "writing at index %d\n", i );
        array[i] = i;
    }
}

int main(int argc,char *argv[])
{
    int x[4];
    _SYM int len;
    //int len=atoi(argv[1]);
    init( x, len );
    assert( x[3] == 3);
}

I added a symbolic value "_SYM int len",  and would like use divine check --symbolic program.bc for the verification. When i used divine cc to generate the bc for the above program.c,  the command is as following:

./divine cc -I/divine-4.1.5_full path/dios/libcxx/include -I/divine-4.1.5_fullpath/dios/libcxxabi/include -I/divine-4.1.5_fullpath/bricks -I/divine-4.1.5_fullpath/lart/abstract program.c

However, it always failed, and the error is as following:/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:96:1: error: unknown type name '_LIBCPP_BEGIN_NAMESPACE_STD'
_LIBCPP_BEGIN_NAMESPACE_STD
^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:98:6: error: expected ';' after top level declarator
class _LIBCPP_TYPE_VIS ios_base;
     ^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:100:1: error: unknown type name 'template'
template<class _CharT>  struct _LIBCPP_TEMPLATE_VIS char_traits;
^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:100:9: error: expected identifier or '('
template<class _CharT>  struct _LIBCPP_TEMPLATE_VIS char_traits;
        ^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:101:1: error: unknown type name 'template'
template<class _Tp>     class _LIBCPP_TEMPLATE_VIS allocator;
^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:101:9: error: expected identifier or '('
template<class _Tp>     class _LIBCPP_TEMPLATE_VIS allocator;
        ^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:103:1: error: unknown type name 'template'
template <class _CharT, class _Traits = char_traits<_CharT> >
^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:103:10: error: expected identifier or '('
template <class _CharT, class _Traits = char_traits<_CharT> >
         ^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:106:1: error: unknown type name 'template'
template <class _CharT, class _Traits = char_traits<_CharT> >
^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:106:10: error: expected identifier or '('
template <class _CharT, class _Traits = char_traits<_CharT> >
         ^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:108:1: error: unknown type name 'template'
template <class _CharT, class _Traits = char_traits<_CharT> >
^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:108:10: error: expected identifier or '('
template <class _CharT, class _Traits = char_traits<_CharT> >
         ^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:110:1: error: unknown type name 'template'
template <class _CharT, class _Traits = char_traits<_CharT> >
^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:110:10: error: expected identifier or '('
template <class _CharT, class _Traits = char_traits<_CharT> >
         ^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:112:1: error: unknown type name 'template'
template <class _CharT, class _Traits = char_traits<_CharT> >
^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:112:10: error: expected identifier or '('
template <class _CharT, class _Traits = char_traits<_CharT> >
         ^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:115:1: error: unknown type name 'template'
template <class _CharT, class _Traits = char_traits<_CharT>,
^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:115:10: error: expected identifier or '('
template <class _CharT, class _Traits = char_traits<_CharT>,
         ^
/home/qian/workspace/divine-4.1.5/dios/libcxx/include/iosfwd:118:1: error: unknown type name 'template'
template <class _CharT, class _Traits = char_traits<_CharT>,


If possible, could you tell me which path i should add when generating the bc for the code with "_SYM"? Thanks a lot!

Best,
Qian

**Comment by vlstill** [comment]
Hi, thanks for the information. The errors you are getting are probably caused by the explicit include paths on your `divine cc` commandline. There shloud be no need to add any include paths, unless you want to add paths to your local headers (e.g. parts of your project). The real problem seems to be that we have probably changed location of the domains.h header without updating documentation. I did not test it with 4.1.5, but on the current develompment version the right way of including it seems to be `#include <rst/domains.h>`. It should be the same for 4.1.5.

However, we are now doing significant changes to the symbolic verification and it is not stable yet. On the current version the verification fails with spurious error. When fixed, it should find invalid memory access, as `len` can larger then 4.

@xlauko, could you please have a look at the code included, there is a spurious `conditional jump depends on an undefined value` on line 8 (current `next`), also please update documentation to match reality.

**Comment by qian-feng** [comment]
Hi, thanks for your information. I changed my demo code based on your advice, and it can generate bc successfully.  However, when i try to check the bc with symbolic value, it seems that it does not conduct the symbolic verification. This could be the spurious error as you mentioned above. The check output is as following:
loading bitcode … LART … RR … constants … done
booting … done
states per second: 54.7945                                                
state count: 4
mips: 0.22
symbolic: 1

error found: yes
error trace: |
  FAULT:  conditional jump depends on an undefined value
  [0] FATAL: control error in userspace

active stack:
  - symbol: void __dios::Fault<__dios::Scheduler<__dios::MachineParams<__dios::MonitorManager<__dios::BaseContext> > > >::handler<__dios::fs::VFS<__dios::ProcessManager<__dios::Fault<__dios::Scheduler<__dios::MachineParams<__dios::MonitorManager<__dios::BaseContext> > > > > > >(_VM_Fault, _VM_Frame*, void (*)())
    location: /dios/include/dios/sys/fault.hpp:193
  - symbol: main
    location: program.c:19
  - symbol: _start
    location: /dios/src/libc/sys/start.cpp:83
a report was written to program.report

If possible, could you tell me which version of divine can address this issue? Thanks a lot.

Best,

Qian

**Comment by xlauko** [comment]
Hi,

actually, it looks that divine found an error in your code:

```cpp
#include <stdio.h>
#include <assert.h>
#include <rst/domains.h>
void init( int *array, int len ) {
    if(len<4) return; // check length
    for ( int i = 0; i <= len; ++i )
    {
        printf( "writing at index %d\n", i );
        array[i] = i;
    }
}

int main(int argc,char *argv[])
{
    int x[4];
    _SYM int len;
    init( x, len );
    assert( x[3] == 3); // conditional jump depends on undefined value here
}
```

The array contains an undefined value, when `len < 4` because you do not initialize it in the `init` function. Also, there is another problem when the `len >= 4` the `init` will cause an array overflow. Actually, I think you wanted to write something like this:

```cpp
#include <stdio.h>
#include <assert.h>
#include <rst/domains.h>
void init( int *array, int len ) {
    for ( int i = 0; i <= len; ++i )
    {
        printf( "writing at index %d\n", i );
        array[i] = i;
    }
}

int main(int argc,char *argv[])
{
    int x[4];
    _SYM int len;
    if ( len < 4 ) {
        init( x, len );
        assert( x[3] == 3 );
   }
}
```
On this program, DIVINE should not report any error. Also I advise you to wait for today's release of DIVINE 4.1.6, which will contain a new version of the symbolic algorithm. In the new version, you will have to create symbolic values by `__VERIFIER_nondet_*` as in other tools (see https://sv-comp.sosy-lab.org/2018/rules.php ).

**Comment by qian-feng** [comment]
Thanks for your time. It works now.
